// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmcdksmgkjfikerrgugy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtY2Rrc21na2pmaWtlcnJndWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDQ2NzQsImV4cCI6MjA3NDU4MDY3NH0.ZWgnKueDL2NS5oywpwGyO5aYbSVEcBMGcm5pct4wYAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});